source "https://rubygems.org"
gem 'jekyll'
gem 'pluto'
gem 'pluto-models'
gem 'nokogiri'
gem 'mini_portile2'
gem 'faraday'
gem 'rake'
gem 'jekyll-paginate-v2'
gem 'jekyll-theme-opensuse', :git => 'https://github.com/opensuse/jekyll-theme.git'
