name: Jekyll Feed Tests

on:
  pull_request:
    paths: &trigger_paths
      - .github/workflows/feeds.yml
      - hackergotchi/*
      - tests/feedcheck*.rb
      - planet.ini
      - Gemfile
      - Gemfile.lock
    branches: &trigger_branches
      - master
  push:
    paths: *trigger_paths
    branches: *trigger_branches
  schedule:
      - cron:  0 9 * * 1
  workflow_dispatch:

permissions: read-all

concurrency:
  group: >-
    ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  feed-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.321.0
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Install Dependencies
        run: bundler install

      - name: Check Feeds
        run: bundle exec ruby tests/feedcheck.rb

      - name: Save Job Summary
        if: failure()
        run: cat error-summary.md >> $GITHUB_STEP_SUMMARY
