name: Jekyll Feed Tests

on:
  push:
    paths:
      - 'hackergotchi/*'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
      - planet.ini
      - Gemfile
      - Gemfile.lock
    branches:
      - master
  pull_request:
    paths:
      - 'hackergotchi/*'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
      - planet.ini
      - Gemfile
      - Gemfile.lock
    branches:
      - master
  schedule:
      - cron:  '0 9 * * 1'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: >-
    ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  feed-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.314.0
        with:
          ruby-version: 4.0
          bundler-cache: true

      - name: Install Dependencies
        run: bundler install

      - name: Check Feeds
        run: bundle exec ruby tests/feedcheck.rb

      - name: Save Job Summary
        if: failure()
        run: cat error-summary.md >> $GITHUB_STEP_SUMMARY
